### ISSUE TITLE
Compilation error caused by FlexibleSUSY

### ISSUE THREAD

**Issue by surrutiaquir** [GambitBSM/gambit_2.4#3]
Hello everyone,
I'm compiling `Gambit`, and everything seems to work fine until the execution of `make gamit` due to an error caused by FlexibleSUSY:

```
[ 12%] Performing build step for 'flexiblesusy'
In file included from src/slha_io.cpp:19:
In file included from src/slha_io.hpp:29:
slhaea/slhaea.h:1522:36: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  struct key_matches : public std::unary_function<value_type, bool>
                              ~~~~~^~~~~~~~~~~~~~
                                   __unary_function
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from src/slha_io.cpp:19:
In file included from src/slha_io.hpp:29:
slhaea/slhaea.h:2358:36: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  struct key_matches : public std::unary_function<value_type, bool>
                              ~~~~~^~~~~~~~~~~~~~
                                   __unary_function
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from src/slha_io.cpp:19:
In file included from src/slha_io.hpp:29:
slhaea/slhaea.h:2379:46: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  struct key_matches_block_def : public std::unary_function<value_type, bool>
                                        ~~~~~^~~~~~~~~~~~~~
                                             __unary_function
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
3 errors generated.
make[4]: *** [src/slha_io.o] Error 1
make[3]: *** [flexiblesusy-prefix/src/flexiblesusy-stamp/flexiblesusy-build] Error 2
make[2]: *** [CMakeFiles/flexiblesusy.dir/all] Error 2
make[1]: *** [CMakeFiles/gambit.dir/rule] Error 2
make: *** [gambit] Error 2
```

How can I overcome this issue? Thanks!

**Comment by andrewfowlie** [comment]
Hi Sebastián,

Thanks for your interest. @pathron may be the best person to answer. It might be relevant that std::unary_func was deprecated in C++11 and removed from C++17 (https://en.cppreference.com/w/cpp/utility/functional/unary_function). 

Andrew

**Comment by tegonzalo** [comment]
Hi,

I presume you are compiling with clang, right? Probably some version > 15. Newer versions of clang are better at keeping up with C++ standards and they have removed the support for the, indeed deprectaed, unary functions. This error happens in SLHAea, which is in turn used by FlexibleSUSY, thereby the error you see. We are aware of this problem and working on a patch to SLHAea to fix it. In the meantime by only recommendation is to downgrade your version of clang.  I can't tell you which is the first version of clang that it fails, but at least I know that it works for 14.0.3 and below.

Cheers,
Tomás

**Comment by andrewfowlie** [comment]
@tegonzalo if I understand correctly, a `--std=c++11` flag cannot help, as this has been removed from Mac equivalent of libstdc++. Is that why downgrading clang would be the only way?

SO tells me gcc has not removed it (yet) but it's probably coming. I didn't realize that this was how deprecated features were handled. I imagined they just kept them in libstdc++ so that people could compile older programs, but that compiling with e.g. `--std=c++17`  would throw a compilation error.

https://stackoverflow.com/questions/51720617/why-does-stdunary-function-still-compile-in-c17

**Comment by tegonzalo** [comment]
Yup, that's all correct.

@surrutiaquir I have now pushed a change to this repo removing the use of  unary functions. Please confirm that it works for you now so we can close this issue

**Comment by surrutiaquir** [comment]
Thanks, @tegonzalo. I downloaded the repo again, but I still get the same errors. I wonder if I need to do something differently.

**Comment by tegonzalo** [comment]
Ah yes, that was my fault. I only changed the `gambit` version of `slhaea`, not the one inside flexiblesusy. Please try again.

**Comment by surrutiaquir** [comment]
Thanks! The compilation does not complain about that anymore but yells at me about this other issue:

```
/Users/suq90/Documents/gambit_2.4/Utils/include/gambit/Utils/util_functions.hpp:134:42: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
    struct EXPORT_SYMBOLS ci_less : std::binary_function<std::string, std::string, bool>
                                    ~~~~~^~~~~~~~~~~~~~~
                                         __binary_function
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/suq90/Documents/gambit_2.4/SpecBit/src/MSSMspec.cpp:19:
In file included from /Users/suq90/Documents/gambit_2.4/SpecBit/include/gambit/SpecBit/MSSMSpec_head.hpp:27:
In file included from /Users/suq90/Documents/gambit_2.4/Elements/include/gambit/Elements/spec.hpp:27:
In file included from /Users/suq90/Documents/gambit_2.4/Elements/include/gambit/Elements/spec_head.hpp:28:
In file included from /Users/suq90/Documents/gambit_2.4/Elements/include/gambit/Elements/subspectrum.hpp:37:
/Users/suq90/Documents/gambit_2.4/Utils/include/gambit/Utils/util_functions.hpp:137:43: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
      struct nocase_compare : public std::binary_function<unsigned char,unsigned char,bool>
                                     ~~~~~^~~~~~~~~~~~~~~
                                          __binary_function
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
2 errors generated.
make[3]: *** [SpecBit/CMakeFiles/SpecBit.dir/src/MSSMspec.cpp.o] Error 1
make[2]: *** [SpecBit/CMakeFiles/SpecBit.dir/all] Error 2
make[1]: *** [CMakeFiles/gambit.dir/rule] Error 2
make: *** [gambit] Error 2
```

I apologize for the inconvenience!

**Comment by tegonzalo** [comment]
I see, so `binary_functions` are deprecated too. I've just removed them, try again please. Apologies for this back and forth, but I don't have a Mac to test these things myself.

**Comment by surrutiaquir** [comment]
Now it compiles perfectly, thanks! There is a Mac-rooted problem with HDF5, so the printer can't be used (I have tried the installation via `brew install hdf5@1.10` in two different machines with the same errors), but other than that, it works like a charm.

```
GAMBIT has exited with fatal exception: GAMBIT error
ERROR: A problem has occurred in the printer utilities.
Failed to open existing HDF5 file, then failed to create new one! (./runs/RHN/samples//RHN.hdf5). The file may exist but be unreadable. You can check this by trying to inspect it with the 'h5ls' command line tool.
Raised at: line 236 in function hid_t Gambit::Printers::HDF5::openFile(const std::string &, bool, bool &, const char) of /Users/suq90/Documents/gambit_2.4/Printers/src/printers/hdf5printer/hdf5tools.cpp.
```

Is this a matter that can be addressed by you (in a different ticket, perhaps), or is it OS-dependent? In any case, feel free to close this query. Many thanks!

**Comment by tegonzalo** [comment]
We have seen this in some systems, depending on the hdf5 installation. In GAMBIT we have two implimentations of the hdf5 printer, and unfortunately the new version is the one causing more problems. Try switching to the old one. For that just change to use the v1 version of the printer, i.e.
```
printer: hdf5_v1
```
in your yaml file. 

I'll close this issue then. Thanks for your feedback and good luck using gambit!
